---
title: "Current Projects"
output:
  distill::distill_article:
    css: postcards.css


---

### *Longitudinal study of gender speech development*
Advisor: Benjamin Munson (University of Minnesota)

In this project, we examine the acoustical difference on the speech of 55 AMAB and 55 AFAB children from 2.5 to 5 years-of-age. Specifically, we look at how F0, acoustic vocal tract length, vowel space size, /s/ acoustics and voice quality contribute to the perceived gender ratings in these children.


Preliminary results of this study was presented in the ASA Fall 2021 meeting in Seattle. 

Wong, E., & Munson, B. (2021). A longitudinal study of gender-specific characteristics of children’s vowels. The Journal of the Acoustical Society of America, 150(4), A152-A152. https://doi.org/10.1121/10.0007954
[**Poster**](https://drive.google.com/file/d/1nzpfmkxjBUkU_2_p_MQYyM_Smql2Hs_5/view?usp=sharing)


---

### *Project H2T: From Hearing to talking: The Sociophonetics of Child-Directed Speech *
Advisor: Benjamin Munson (University of Minnesota)

One way that children might learn gendered speech is through child-directed speech. Here we examine how mothers of AMAB vs. AFAB children talk. 


---

### *Project WhIMS: Who is my Model for Speech? Development of Gendered Speech in Children*
Advisors/Mentos: Benjamin Munson, Melissa Koenig & Charisse Pickron (University of Minnesota)

Another possible way for children to learn gendered speech is to imitate a speaker "model" whom they evaluate favourably. In this project, we examine how children’s social preferences are influenced by gender information conveyed by speech versus by faces, and whether this social preferences motivate children's learning of gendered speech.


---

### *Identifying language impairment in diverse multilingual children*
Advisors: Kerry Ebert & Lizbeth Finestack (University of Minnesota)

This project validates the use of dynamic and processing-based assessments for identifying developmental language disorder (DLD) in multilingual children. This is because traditional methods of language assessment compares a multilingual child's performance to those of monolingual English children, which  often lead to discrepancies in assessment performances in this diverse population. 

My role in this project is to modify test materials, collect and analyze data from Mandarin-English and Cantonese-English bilingual children. 

Poster presentations:
Wong, E. and Ebert, K. (2023). An alternative scoring method to reduce bias in nonword repetition for bilingual children. Symposium on Research in Child Language Disorders. Madison, WI. June 1-3. [**Poster**](https://drive.google.com/file/d/1NnfPB8cHyjUwC4fhCxp2KhwfDmPohxR8/view?usp=sharing)

Kerry, E., Finestack, L., Kuchler, K. & Wong, E. (2023). Towards less-biased language assessment: Exploring dynamic and processing-based assessments in diverse bilingual children. Symposium on Research in Child Language Disorders. Madison, WI. June 1-3. 

---

### *Voice Quality features of Hong Kong Cantonese and Guangzhou Cantonese*
Collaborator: Roxana Fung (HKPolyU)

Hong Kong Cantonese (HKC) and Guangzhou Cantonese (GZC) are two regional accents of Cantonese. They share the same phonetic inventory except for the high-level tone (55) that could be realized with a high-falling tone (53) in older GZC speakers. However, native speakers can often distinguish the two accents without the cue of the high-falling tone. In this project, we look at what phonetic features distinguish the two Cantonese accents. 

### Part 1
In this study, we look at the voice quality features of the two accents, and the development of these features between various age groups. We examined the speech of 191 Cantonese talkers of three age groups from the two cities. We conducted auditory and acoustic analysis of the voice quality features.  

Preliminary results of this study were presented in:

Fung, R. and Wong, Y-C. (2017). The voice quality differences between Hong Kong Cantonese and Guangzhou Cantonese. The 22nd JWLLP & The 5th Workshop on VariAMU. The Hong Kong Polytechnic University, Hong Kong, April 8th, 2017.

Fung, R. and Wong, E. (2017). The differences in voice quality between Hong   Kong Cantonese and Guangzhou Cantonese. UChicago Linguistic Research Forum. The Chinese University of Hong Kong, Hong Kong, March 17th, 2017.


### Part 2
We further collected acoustic and EGG data from text-reading and free speech tasks to examine the articulation and acoustic variations between the two groups of talkers. Data Analysis is on-going.


